AllCops:
  Exclude:
    - 'bin/*'
    - 'sorbet/*'
    - '.idea/*'
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 100
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
